[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_ai_nexus = "6gT2Yv1C1RdgN8ABQrbQ9dzzMbKVjLtRJ45ziSkN6nZc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
max_program_size_limit = 2000000
