[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_ai_nexus = "4zDxXREBd1irbagc7gvuaxHdfeYamiudBtoe8XbXuY9q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./program-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
max_program_size_limit = 2000000
